apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-shop
  annotations:
    argocd-image-updater.argoproj.io/image-list: shop=azmatahmed/devops-shop
    argocd-image-updater.argoproj.io/shop.update-strategy: latest
    argocd-image-updater.argoproj.io/shop.allow-tags: regexp:^[0-9]+$
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-shop
  template:
    metadata:
      labels:
        app: devops-shop
    spec:
      containers:
      - name: devops-shop
        image: azmatahmed/devops-shop:3
        ports:
        - containerPort: 3000

