apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-shop-ingress
spec:
  rules:
  - host: shop.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-shop-service
            port:
              number: 80
