apiVersion: v1
kind: Service
metadata:
  name: devops-shop-service
spec:
  type: NodePort      # So you can access it locally
  selector:
    app: devops-shop
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30007
